a = input('Digite algo:')
print('O tipo primitvo desse valor é', type(a))
print('Contém apenas espaços?', a.isspace())
print('É númerico?',  a.isnumeric())
print('É alfabético?', a.isalpha())
print('É alfanúmerico?', a.isalnum())
print('Está tudo escrito em maiúsculo?', a.isupper())
print('Está tudo escrito em minúsculo?', a.islower())
print('Está capitalizada?', a.istitle())
